"""Added extra fields for user

Revision ID: b664d63b318a
Revises: 12b43de90bc0
Create Date: 2021-01-17 14:38:57.158010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b664d63b318a'
down_revision = '12b43de90bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('alternative_email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    op.drop_column('users', 'status')
    op.drop_column('users', 'country')
    op.drop_column('users', 'city')
    op.drop_column('users', 'alternative_email')
    # ### end Alembic commands ###
