"""empty message

Revision ID: 20aa8d535bb9
Revises: d3f8a8d3d8fe
Create Date: 2021-01-03 11:26:45.323139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20aa8d535bb9'
down_revision = 'd3f8a8d3d8fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('genres', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('href', sa.String(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('external_urls', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlists',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('track_total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artisttracks',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('artist_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('track_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artisttracks_artist_id'), 'artisttracks', ['artist_id'], unique=False)
    op.create_index(op.f('ix_artisttracks_track_id'), 'artisttracks', ['track_id'], unique=False)
    op.create_table('playlisttracks',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('track_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('playlist_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('added_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlisttracks_playlist_id'), 'playlisttracks', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_playlisttracks_track_id'), 'playlisttracks', ['track_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playlisttracks_track_id'), table_name='playlisttracks')
    op.drop_index(op.f('ix_playlisttracks_playlist_id'), table_name='playlisttracks')
    op.drop_table('playlisttracks')
    op.drop_index(op.f('ix_artisttracks_track_id'), table_name='artisttracks')
    op.drop_index(op.f('ix_artisttracks_artist_id'), table_name='artisttracks')
    op.drop_table('artisttracks')
    op.drop_table('tracks')
    op.drop_table('playlists')
    op.drop_table('artists')
    # ### end Alembic commands ###
