"""Added by column to playlist tracks

Revision ID: 7db0ac809d99
Revises: c5f05871ebe3
Create Date: 2021-01-16 13:05:44.623373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7db0ac809d99'
down_revision = 'c5f05871ebe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playlist_tracks', 'added_by',
                    existing_type=sa.VARCHAR(),
                    type_=postgresql.UUID(),
                    postgresql_using='added_by::uuid',
                    nullable=True)
    op.execute("""UPDATE playlist_tracks SET added_by = playlists.user_id
     FROM playlists WHERE playlist_tracks.playlist_id = playlists.id""")
    op.alter_column('playlist_tracks', 'added_by',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.create_index(op.f('ix_playlist_tracks_added_by'), 'playlist_tracks', ['added_by'], unique=False)
    op.create_foreign_key('fk_playlist_tracks_added_by_user', 'playlist_tracks', 'users', ['added_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_playlist_tracks_added_by_user', 'playlist_tracks', type_='foreignkey')
    op.drop_index(op.f('ix_playlist_tracks_added_by'), table_name='playlist_tracks')
    op.alter_column('playlist_tracks', 'added_by',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.execute("""UPDATE playlist_tracks SET added_by = NULL""")
    # ### end Alembic commands ###
